import asyncio
import pytest
from fastapi.testclient import TestClient
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from starlette.websockets import WebSocketDisconnect

from src.core.database import Base, get_db
from src.main import app

TEST_DATABASE_URL = "sqlite+aiosqlite:///:memory:"

engine = create_async_engine(
    TEST_DATABASE_URL,
    echo=False,
    future=True,
    connect_args={"check_same_thread": False},
)

SessionFactory = async_sessionmaker(
    bind=engine,
    class_=AsyncSession,
    expire_on_commit=False,
    autoflush=False,
)

async def _initialize_test_db() -> None:
    import src.models.ticket  # noqa: F401

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

asyncio.run(_initialize_test_db())

async def override_get_db() -> AsyncSession:
    async with SessionFactory() as session:
        try:
            yield session
        finally:
            await session.close()

@pytest.fixture(autouse=True)
def sqlite_db_override() -> None:
    original = app.dependency_overrides.get(get_db)
    app.dependency_overrides[get_db] = override_get_db
    try:
        yield
    finally:
        if original is None:
            app.dependency_overrides.pop(get_db, None)
        else:
            app.dependency_overrides[get_db] = original


def test_websocket_auth_success() -> None:
    """Verify that a WebSocket connection succeeds with a valid token."""
    client = TestClient(app)
    with client.websocket_connect("/ws/tickets?token=supportflow-websocket-token") as websocket:
        assert websocket is not None


def test_websocket_auth_failure() -> None:
    """Verify that a WebSocket connection fails with code 1008 for an invalid token."""
    client = TestClient(app)
    with pytest.raises(WebSocketDisconnect) as exc_info:
        with client.websocket_connect("/ws/tickets?token=invalid-token"):
            pass
    assert exc_info.value.code == 1008


def test_websocket_broadcast() -> None:
    """Verify that a broadcast message is received by all active connections."""
    client = TestClient(app)
    with client.websocket_connect("/ws/tickets?token=supportflow-websocket-token") as ws1:
        with client.websocket_connect("/ws/tickets?token=supportflow-websocket-token") as ws2:
            # Standardized schema event
            event_payload = {
                "event": "TICKET_CREATED",
                "timestamp": "2026-08-03T19:08:15Z",
                "data": {"ticket_id": 123, "status": "OPEN"}
            }
            # Broadcast the event payload
            asyncio.run(app.state.ws_manager.broadcast(event_payload))
            
            # Receive and assert
            data1 = ws1.receive_json()
            data2 = ws2.receive_json()
            
            assert data1 == event_payload
            assert data2 == event_payload


def test_websocket_disconnect_cleanup() -> None:
    """Verify that client disconnections correctly update active_connections."""
    client = TestClient(app)
    initial_count = len(app.state.ws_manager.active_connections)
    
    with client.websocket_connect("/ws/tickets?token=supportflow-websocket-token"):
        assert len(app.state.ws_manager.active_connections) == initial_count + 1
        
    assert len(app.state.ws_manager.active_connections) == initial_count


def test_triage_endpoint_broadcasts_to_websocket_clients() -> None:
    """Validate that triage endpoint results are broadcast to connected websocket clients."""
    client = TestClient(app)

    with client.websocket_connect("/ws/tickets?token=supportflow-websocket-token") as ws1:
        with client.websocket_connect("/ws/tickets?token=supportflow-websocket-token") as ws2:
            # Create a new ticket before triage and consume the create broadcast event first.
            create_response = client.post(
                "/api/v1/tickets/",
                json={
                    "title": "Streaming event test",
                    "description": "Verify websocket broadcast on triage.",
                    "customer_email": "notify@supportflow.com",
                    "priority": "MEDIUM",
                },
            )
            assert create_response.status_code == 201
            ticket_id = create_response.json()["id"]

            # Drain the TICKET_CREATED events generated by ticket creation.
            assert ws1.receive_json()["event"] == "TICKET_CREATED"
            assert ws2.receive_json()["event"] == "TICKET_CREATED"

            # Triage the ticket via HTTP endpoint which should emit a broadcast event.
            triage_response = client.post(f"/api/v1/tickets/{ticket_id}/triage")
            assert triage_response.status_code == 200

            event1 = ws1.receive_json()
            event2 = ws2.receive_json()

            assert event1["event"] in ("TICKET_TRIAGED", "TICKET_ESCALATED")
            assert event2["event"] in ("TICKET_TRIAGED", "TICKET_ESCALATED")
            assert event1 == event2
            assert event1["data"]["ticket_id"] == str(ticket_id)
            assert event1["data"]["status"] in ("RESOLVED", "IN_PROGRESS")
            assert event1["data"]["priority"] in ("LOW", "MEDIUM", "HIGH", "URGENT")
            assert isinstance(event1["timestamp"], str)
